language: python
os:
  - linux
  - osx

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - pip install -r .travis-requirements.txt
  - pip install --editable .

script: make test