language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V

install:
  - pip install -r .travis-requirements.txt
  - pip install --editable .
  - socl me
  - pip uninstall .
  - pip3 install -r .travis-requirements.txt
  - pip3 install --editable .
  - socl me

script: make test
